
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sikyaqsurjgsobxxbgml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpa3lhcXN1cmpnc29ieHhiZ21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjY3MjEsImV4cCI6MjA2MTQwMjcyMX0.nXvKW91njEss-n-l8A3w-bKfGJdp4t9q-XuFK5Qza8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
